name: Build Authentik Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Build Environment
        run: |
          docker pull gotify/build:1.24.1-linux-amd64

      - name: Build the Plugin
        run: |
          docker run --rm -v "$PWD/.:/proj" -w /proj gotify/build:1.24.1-linux-amd64 \
            go build -a -installsuffix cgo -ldflags "-w -s" -buildmode=plugin -o plugin/authentik-plugin-amd64.so /proj

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: plugin/authentik-plugin-amd64.so
